
name: OpenWrt-Builder

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

    - name: Delete Tags without Release
      uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
